In [1]:
import time

In [2]:
time.strftime('%c', time.localtime(time.time()))

'Thu Jul 15 10:04:44 2021'

In [3]:
#단일 레이어 퍼셉트론으로는 xor 해결 불가, 여러 레이어가 있어야 함

In [4]:
#backpropagation : loss(cost)를 weight에 대해 미분함 

In [5]:
x = torch.FloatTensor([[0, 0], [1, 0], [0, 1], [1, 1]])

NameError: name 'torch' is not defined

In [6]:
import torch

In [7]:
x = torch.FloatTensor([[0, 0], [1, 0], [0, 1], [1, 1]])

In [8]:
y = torch.FloatTensor([[0],[1], [1], [0]])

In [9]:
#nn layers

In [10]:
w1 = torch.Tensor(2, 2)

In [11]:
b1 = torch.Tensor(2)

In [12]:
w2 = torch.Tensor(2, 1)

In [13]:
b2 = torch.Tensor(1)

In [14]:
def sigmoid(x):
    return 1.0/(1.0 + torch.exp(-x))

In [15]:
def sigmoid_prime(x):
    return sigmoid(x)*(1 - sigmoid(x))

In [16]:
#sigmoid 미분한 거임

In [17]:
for step in range(10001):
    l1 = torch.add(torch.matmul(x, w1), b1)
    a1 = sigmoid(l1)
    l2 = torch.add(torch.matmul(a1, w2), b2)
    y_pred = sigmoid(l2)
    
    cost = -torch.mean(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred))
    
    #back propagation
    d_y_pred = (y_pred - y)/(y_pred * (1.0 - y_pred) + 1e-7)
    
    d_l2 = d_y_pred * sigmoid_prime(l2)
    d_b2 = d_l2
    d_w2 = torch.matmul(torch.transpose(a1, 0, 1), d_b2)
    
    d_a1 = torch.matmul(d_b2, torch.transpose(w2, 0, 1))
    d_l1 = d_a1 * sigmoid_prime(l1)
    d_b1 = d_l1
    d_w1 = torch.matmul(torch.transpose(x, 0, 1), d_b1)
    
    #weight_update
    lr= 0.1
    w1 -= d_w1 * lr
    b1 -= torch.mean(d_b1, 0) * lr
    w2 -= d_w2 * lr
    b2 -= torch.mean(d_b2, 0) * lr
    
    if step%100 == 0:
        print(step, cost.item())

0 0.6931471824645996
100 0.6931471824645996
200 0.6931471824645996
300 0.6931471824645996
400 0.6931471824645996
500 0.6931471824645996
600 0.6931471824645996
700 0.6931471824645996
800 0.6931471824645996
900 0.6931471824645996
1000 0.6931471824645996
1100 0.6931471824645996
1200 0.6931471824645996
1300 0.6931471824645996
1400 0.6931471824645996
1500 0.6931471824645996
1600 0.6931471824645996
1700 0.6931471824645996
1800 0.6931471824645996
1900 0.6931471824645996
2000 0.6931471824645996
2100 0.6931471824645996
2200 0.6931471824645996
2300 0.6931471824645996
2400 0.6931471824645996
2500 0.6931471824645996
2600 0.6931471824645996
2700 0.6931471824645996
2800 0.6931471824645996
2900 0.6931471824645996
3000 0.6931471824645996
3100 0.6931471824645996
3200 0.6931471824645996
3300 0.6931471824645996
3400 0.6931471824645996
3500 0.6931471824645996
3600 0.6931471824645996
3700 0.6931471824645996
3800 0.6931471824645996
3900 0.6931471824645996
4000 0.6931471824645996
4100 0.6931471824645996
4200

In [18]:
x

tensor([[0., 0.],
        [1., 0.],
        [0., 1.],
        [1., 1.]])

In [19]:
y

tensor([[0.],
        [1.],
        [1.],
        [0.]])

In [20]:
linear1 = torch.nn.linear(2, 2, bias = True)

AttributeError: module 'torch.nn' has no attribute 'linear'

In [21]:
linear1 = torch.nn.Linear(2, 2, bias = True)

In [22]:
linear2 = torch.nn.Linear(2, 1, bias = True)

In [23]:
sigmoid = torch.nn.Sigmoid()

In [24]:
model = torch.nn.Sequential(linear1, sigmoid, linear2, sigmoid)

In [25]:
criteration = torch.nn.BCELoss()

In [26]:
optimizer = torch.optim.SGD(model.parameters(), lr = 1)

In [27]:
for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(x)
    
    cost = criteration(hypothesis, y)
    cost.backward()
    optimizer.step()
    if step % 100 == 0:
        print(step, cost.item)

0 <built-in method item of Tensor object at 0x7f91e9a1e640>
100 <built-in method item of Tensor object at 0x7f91e9a1e680>
200 <built-in method item of Tensor object at 0x7f91e9a1e6c0>
300 <built-in method item of Tensor object at 0x7f91e9a1e700>
400 <built-in method item of Tensor object at 0x7f91e9a1e7c0>
500 <built-in method item of Tensor object at 0x7f91e9a14dc0>
600 <built-in method item of Tensor object at 0x7f91e8855d40>
700 <built-in method item of Tensor object at 0x7f91e9a1e680>
800 <built-in method item of Tensor object at 0x7f91e9a1e880>
900 <built-in method item of Tensor object at 0x7f91e9a1e700>
1000 <built-in method item of Tensor object at 0x7f91e9a1e6c0>
1100 <built-in method item of Tensor object at 0x7f91e9a1ea80>
1200 <built-in method item of Tensor object at 0x7f91e9a17ec0>
1300 <built-in method item of Tensor object at 0x7f91e9a14c00>
1400 <built-in method item of Tensor object at 0x7f91e9a1ea00>
1500 <built-in method item of Tensor object at 0x7f91e9a1e9c0>
1600

In [28]:
cost.item()

0.0010024596704170108

In [29]:
model(x)

tensor([[9.5793e-04],
        [9.9868e-01],
        [9.9911e-01],
        [8.3390e-04]], grad_fn=<SigmoidBackward>)