In [1]:
import torch

In [2]:
import time

In [3]:
import torch.nn as nn


In [4]:
import torch.nn.functional as F

In [5]:
import torch.optim as optim

In [6]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]

In [7]:
y_data = [[0], [0], [0], [1], [1], [1]

SyntaxError: unexpected EOF while parsing (<ipython-input-7-5b72b7b0e30b>, line 1)

In [8]:
y_data = [[0], [0], [0], [1], [1], [1]]

In [9]:
x_train = torch.FloatTensor(x_data)

In [10]:
y_train = torch.FloatTensor(y_data)

In [11]:
print(x_train.shape)

torch.Size([6, 2])


In [12]:
print(torch.exp(1))

TypeError: exp(): argument 'input' (position 1) must be Tensor, not int

In [13]:
W = torch.zeros((2, 1), requires_grad = True)

In [14]:
b = torch.zeros(1, requires_grad = True)

In [15]:
hypothesis = 1/(1 + torch.exp(-(x_train.matmul(W)+b)))

In [16]:
hypothesis

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)

In [17]:
#or, equivalently, 
hypothesis = torch.sigmoid(x_train.matmul(W)+b)

In [18]:
hypothesis

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)

In [19]:
torch.average

AttributeError: module 'torch' has no attribute 'average'

In [20]:
torch.mean

<function _VariableFunctionsClass.mean>

In [21]:
torch.log

<function _VariableFunctionsClass.log>

In [22]:
torch.log(10)

TypeError: log(): argument 'input' (position 1) must be Tensor, not int

In [23]:
torch.log(torch.FloatTensor(10))

tensor([     -inf,       nan,       nan,       nan, -100.7140,      -inf,
             -inf,      -inf,      -inf,      -inf])

In [24]:
torch.log(torch.FloatTensor([10]))

tensor([2.3026])

In [25]:
cost = torch.mean(y_train*torch.log(hypothesis)+(1-y_train)*(torch.log(1-hypothesis)))

In [26]:
cost

tensor(-0.6931, grad_fn=<MeanBackward0>)

In [27]:
1-y_train


tensor([[1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.]])

In [28]:
F.binary_cross_entropy(hyopthesis, y_train)

NameError: name 'hyopthesis' is not defined

In [29]:
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

In [30]:
optimizer = optim.SGD([W, b], lr = 1)

In [31]:
nb_epochs = 1000

In [32]:
for epoch in in range(nb_epochs + 1):
    #Cost evaluation
    hypothesis = torch.sigmoid(x_train.matmul(W)+b)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0: 
        print("Epoch {:4d}/{} Cost : {:.6f}".format(epoch, nb_epochs, cost.item()))

SyntaxError: invalid syntax (<ipython-input-32-bf1a1042f32b>, line 1)

In [33]:
for epoch in range(nb_epochs + 1):
    #Cost evaluation
    hypothesis = torch.sigmoid(x_train.matmul(W)+b)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0: 
        print("Epoch {:4d}/{} Cost : {:.6f}".format(epoch, nb_epochs, cost.item()))

Epoch    0/1000 Cost : 0.693147
Epoch  100/1000 Cost : 0.134722
Epoch  200/1000 Cost : 0.080643
Epoch  300/1000 Cost : 0.057900
Epoch  400/1000 Cost : 0.045300
Epoch  500/1000 Cost : 0.037261
Epoch  600/1000 Cost : 0.031672
Epoch  700/1000 Cost : 0.027556
Epoch  800/1000 Cost : 0.024394
Epoch  900/1000 Cost : 0.021888
Epoch 1000/1000 Cost : 0.019852


In [34]:
W

tensor([[3.2530],
        [1.5179]], requires_grad=True)

In [35]:
b

tensor([-14.4819], requires_grad=True)

In [36]:
torch.sigmoid(x_train.matmul(W) + b)

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward>)

In [37]:
time.strftime('%c', time.localtime(time.time()))

'Mon Jul  5 11:17:30 2021'