In [1]:
import pytorch


ModuleNotFoundError: No module named 'pytorch'

In [2]:
import torch

In [1]:
x_train = torch.FloatTensor([[1], [2], [3]])

NameError: name 'torch' is not defined

In [2]:
torch

NameError: name 'torch' is not defined

In [3]:
import torch

In [4]:
x_train = torch.FloatTensor([[1], [2], [3]])




In [5]:
y_train = torch.FloatTensor([[2], [4], [6]])

In [6]:
W = torch.zeros(1, requires_grad = True)

In [7]:
b = torch.zeros(1, requires_grad = True)

In [8]:
hypothesis = W*x_train+b

In [9]:
hypothesis

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

In [10]:
cost = torch.mean((hypothesis-y_train)**2)

In [11]:
cost


tensor(18.6667, grad_fn=<MeanBackward0>)

In [12]:
optim

NameError: name 'optim' is not defined

In [13]:
optim.SGD

NameError: name 'optim' is not defined

In [14]:
torch.optim

<module 'torch.optim' from '/Users/yunho/opt/anaconda3/lib/python3.8/site-packages/torch/optim/__init__.py'>

In [15]:
import torch.optim as optim

In [16]:
optim

<module 'torch.optim' from '/Users/yunho/opt/anaconda3/lib/python3.8/site-packages/torch/optim/__init__.py'>

In [17]:
optimizer = optim.SGD([W, b], 1r = 0.01)

SyntaxError: invalid syntax (<ipython-input-17-c0a6ee9e7012>, line 1)

In [18]:
optimizer = optim.SGD([W, b], lr = 0.01)

In [19]:
nb_epochs = 1000


In [20]:
for epoch in range(1, nb_epochs+1):

SyntaxError: unexpected EOF while parsing (<ipython-input-20-fb55a86371fc>, line 1)

In [21]:
for epoch in range(1, nb_epochs+1):
    hypothesis = W*x_train+b
    cost = torch.mean((hypothesis-y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

In [22]:
W

tensor([1.9708], requires_grad=True)

In [23]:
b

tensor([0.0664], requires_grad=True)