In [1]:
import torch

In [2]:
import torch.nn as nn

In [3]:
import torch.nn.functional as F

In [4]:
import torch.optim as optim

In [5]:
torch.manual_seed(1)

In [6]:
import time


In [7]:
time.strftime('%Y-%m-%d', time.localtime(time.time()))

'2021-07-11'

In [8]:
time.strftime('%c', time.localtime(time.time()))

'Sun Jul 11 13:50:03 2021'

In [9]:
x_train = torch.FloatTensor([[1, 2, 1],
                            [1, 3, 2],
                            [1, 3, 4],
                            [1, 5, 5],
                            [1, 7, 5],
                            [1, 2, 5],
                            [1, 6, 6],
                            [1, 7, 7]])

In [10]:
y_train = torch.FloatTensor([2, 2, 2, 1, 1, 1, 0, 0])

In [11]:
x_test = torch.FloatTensor([[2, 1, 1], [3, 1, 2], [3, 3, 4]])

In [12]:
y_test = torch.FloatTensor([2, 2, 2])

In [13]:
class SoftmaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.linear(3, 3)
    def forward(self, x):
        return self.linear(x)

In [14]:
model = SoftmaxClassifierModel()

AttributeError: module 'torch.nn' has no attribute 'linear'

In [15]:
class SoftmaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.data = 3
    def forward(self, x):
        return self.data

In [16]:
model = SoftmaxClassifierModel()

In [17]:
model.data

3

In [18]:
class SoftmaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 3)
    def forward(self, x):
        return self.linear(x)

In [19]:
model = SoftmaxClassifierModel()

In [20]:
optimizer = optim.SGD(model.parameters(), lr = 0.1)

In [21]:
a = nn.Linear(2, 4)

In [22]:
a

Linear(in_features=2, out_features=4, bias=True)

In [23]:
print(a)

Linear(in_features=2, out_features=4, bias=True)


In [24]:
a[0]

TypeError: 'Linear' object is not subscriptable

In [25]:
dir(a)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__constants__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_call_impl',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_backward_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_named_members',
 '_non_persistent_buffers_set',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_dict_hooks',
 '_version',
 'add_m

In [26]:
a.cpu

<bound method Module.cpu of Linear(in_features=2, out_features=4, bias=True)>

In [27]:
def train(model, optimizer, x_train, y_train):
    nb_epochs = 20
    for epoch in range(nb_epochs):
        prediction = model(x_train)
        cost = F.cross_entropy(prediction, y_train)
        
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        print('Epoch {:4d}/{} Cost : {:.6f}'.format(epoch, nb_epochs, cost.item()))

In [28]:
def test(model, optimizer, x_train, y_train):
    prediction = model(x_test)
    predicted_class = prediction.max(1)[1]
    correct_count = (predicted_class == y_train).sum().item()
    cost = F.cross_entropy(prediction, y_test)
    print('Accuracy : {}% Cost : {:6f}'.format(correct_count/len(y_test)*100, cost.item()))

In [29]:
a.item()

AttributeError: 'Linear' object has no attribute 'item'

In [30]:
type(a)

torch.nn.modules.linear.Linear

In [31]:
a(3)

TypeError: linear(): argument 'input' (position 1) must be Tensor, not int

In [32]:
train(model, optimizer, x_train, y_train)

RuntimeError: expected scalar type Long but found Float

In [33]:
type(type(1))

type

In [34]:
type(1) = 3

SyntaxError: cannot assign to function call (<ipython-input-34-983968b9d39a>, line 1)

In [35]:
model([[1, 2, 3]])

TypeError: linear(): argument 'input' (position 1) must be Tensor, not list

In [36]:
model(torch.FloatTensor([[1, 2, 3]]))

tensor([[-0.6186,  0.3828,  0.7379]], grad_fn=<AddmmBackward>)

In [37]:
p = model(torch.FloatTensor([[1, 2, 3
                    ]]))

In [38]:
p

tensor([[-0.6186,  0.3828,  0.7379]], grad_fn=<AddmmBackward>)

In [39]:
F.cross_entropy(p, torch.FloatTensor([[0, 0, 1]]))

RuntimeError: 1D target tensor expected, multi-target not supported

In [40]:
F.cross_entropy(p, torch.FloatTensor([0, 0, 1]))

ValueError: Expected input batch_size (1) to match target batch_size (3).

In [41]:
F.cross_entropy(p, torch.FloatTensor([0, 0, 1]))

ValueError: Expected input batch_size (1) to match target batch_size (3).

In [42]:
F.cross_entropy(p, torch.FloatTensor([
    
1]))

RuntimeError: expected scalar type Long but found Float

In [43]:
F.cross_entropy(p, torch.LongTensor([1]))

tensor(1.0274, grad_fn=<NllLossBackward>)

In [44]:
p

tensor([[-0.6186,  0.3828,  0.7379]], grad_fn=<AddmmBackward>)

In [45]:
F.cross_entropy(p, torch.LongTensor([0]))

tensor(2.0288, grad_fn=<NllLossBackward>)

In [46]:
F.cross_entropy(p, torch.LongTensor([2]))

tensor(0.6722, grad_fn=<NllLossBackward>)

In [47]:
F.cross_entropy(p, torch.LongTensor([3]))

IndexError: Target 3 is out of bounds.

In [48]:
a = torch.LongTensor(y_train)

TypeError: expected TensorOptions(dtype=long long, device=cpu, layout=Strided, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)) (got TensorOptions(dtype=float, device=cpu, layout=Strided, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)))

In [49]:
def train(model, optimizer, x_train, y_train):
    nb_epochs = 20
    for epoch in range(nb_epochs):
        prediction = model(x_train)
        cost = F.cross_entropy(prediction, y_train.long())
        
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        print('Epoch {:4d}/{} Cost : {:.6f}'.format(epoch, nb_epochs, cost.item()))

In [50]:
train(model, optimizer, x_train, y_train)

Epoch    0/20 Cost : 2.203667
Epoch    1/20 Cost : 1.199645
Epoch    2/20 Cost : 1.142985
Epoch    3/20 Cost : 1.117769
Epoch    4/20 Cost : 1.100901
Epoch    5/20 Cost : 1.089523
Epoch    6/20 Cost : 1.079872
Epoch    7/20 Cost : 1.071320
Epoch    8/20 Cost : 1.063325
Epoch    9/20 Cost : 1.055720
Epoch   10/20 Cost : 1.048378
Epoch   11/20 Cost : 1.041245
Epoch   12/20 Cost : 1.034285
Epoch   13/20 Cost : 1.027478
Epoch   14/20 Cost : 1.020813
Epoch   15/20 Cost : 1.014279
Epoch   16/20 Cost : 1.007872
Epoch   17/20 Cost : 1.001586
Epoch   18/20 Cost : 0.995419
Epoch   19/20 Cost : 0.989365


In [51]:
test(model, optimizer, x_test, y_test)

RuntimeError: expected scalar type Long but found Float

In [52]:
def test(model, optimizer, x_train, y_train):
    prediction = model(x_test)
    predicted_class = prediction.max(1)[1]
    correct_count = (predicted_class == y_train).sum().item()
    cost = F.cross_entropy(prediction, y_test.long())
    print('Accuracy : {}% Cost : {:6f}'.format(correct_count/len(y_test)*100, cost.item()))

In [53]:
test(model, optimizer, x_test, y_test)

Accuracy : 0.0% Cost : 1.425844


In [54]:
test(model, optimizer, x_train, y_train)

RuntimeError: The size of tensor a (3) must match the size of tensor b (8) at non-singleton dimension 0

In [55]:
model = SoftmaxClassifierModel()

In [56]:
optimizer = optim.SGD(model.parameters(), lr = 1e5)

In [57]:
train(model, optimizer, x_train, y_train)

Epoch    0/20 Cost : 3.187324
Epoch    1/20 Cost : 1100707.500000
Epoch    2/20 Cost : 2482261.250000
Epoch    3/20 Cost : 664769.937500
Epoch    4/20 Cost : 1668198.750000
Epoch    5/20 Cost : 748657.750000
Epoch    6/20 Cost : 1353832.500000
Epoch    7/20 Cost : 1790073.750000
Epoch    8/20 Cost : 917894.937500
Epoch    9/20 Cost : 989687.125000
Epoch   10/20 Cost : 990845.250000
Epoch   11/20 Cost : 1585082.500000
Epoch   12/20 Cost : 1265073.750000
Epoch   13/20 Cost : 1149145.000000
Epoch   14/20 Cost : 589766.937500
Epoch   15/20 Cost : 689678.625000
Epoch   16/20 Cost : 983032.687500
Epoch   17/20 Cost : 1265073.750000
Epoch   18/20 Cost : 1686645.000000
Epoch   19/20 Cost : 484999.593750


In [58]:
#overshoot
